### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by Mistic92** [reedom/casbin-firestore-adapter#2]
Hi, is this project still supported? Where can I find working example? I have tried to use it with casbin and local Firestore emulator but it's not doing anything and not throwing any errors.

**Comment by hsluoyz** [comment]
@reedom

**Comment by reedom** [comment]
@Mistic92 @hsluoyz 
For reading, I think [echo-middleware-casbin](https://github.com/reedom/echo-middleware-casbin) could be a working example.
